/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tortasdominio.presentacion;

import com.mycompany.tortasdominio.entidades.Orden;
import com.mycompany.tortasdominio.entidades.Producto;
import com.mycompany.tortasdominio.subsistemas.orden.FacadeAdminOrden;
import com.mycompany.tortasdominio.subsistemas.orden.IAdminOrden;
import com.mycompany.tortaspersistencia.dtos.NuevoProductoDTO;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author crist
 */
public class Ordenes extends javax.swing.JFrame {

    List<Orden> listaOrden;

    /**
     * Creates new form Ordenes
     *
     * @param listaOrden
     */
    public Ordenes(List<Orden> listaOrden) {
        initComponents();
        llenarTabla(listaOrden);
    }

    private void llenarTabla(List<Orden> listaOrden) {
        DefaultTableModel ordenesEncontradas = new DefaultTableModel();
        ordenesEncontradas.addColumn("Nombre");
        ordenesEncontradas.addColumn("Productos");
        ordenesEncontradas.addColumn("Total");
        ordenesEncontradas.addColumn("Estado");
        ordenesEncontradas.addColumn("Número de orden");
        ordenesEncontradas.addColumn("Fecha");

//        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy", Locale.getDefault());
        for (Orden orden : listaOrden) {
            StringBuilder productosString = new StringBuilder();
            for (Producto producto : orden.getProductos()) {
                productosString.append(producto.getNombre()).append(" x").append(producto.getCantidad()).append(", ");
            }
            String productosFormatted = productosString.toString();
            if (productosFormatted.length() > 2) {
                productosFormatted = productosFormatted.substring(0, productosFormatted.length() - 2); // Remove the trailing comma and space
            }
            Object[] fila = {
                orden.getNombreCliente(),
                productosFormatted,
                orden.getTotal(),
                orden.getEstado(),
                orden.getNumeroOrden(),
                orden.getFecha()
            };
            ordenesEncontradas.addRow(fila);
        }
        jTPOrden.setModel(ordenesEncontradas);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eliminarrBoton = new javax.swing.JButton();
        entregadaBoton = new javax.swing.JButton();
        tablaOrdenes = new javax.swing.JScrollPane();
        jTPOrden = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eliminarrBoton.setText("cancelada");
        eliminarrBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarrBotonActionPerformed(evt);
            }
        });

        entregadaBoton.setText("entregada");
        entregadaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregadaBotonActionPerformed(evt);
            }
        });

        jTPOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre ", "Productos", "Total", "Estado", "Numero de orden", "Fecha"
            }
        ));
        tablaOrdenes.setViewportView(jTPOrden);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(eliminarrBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(entregadaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tablaOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tablaOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entregadaBoton)
                            .addComponent(eliminarrBoton))
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarrBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarrBotonActionPerformed
        // TODO add your handling code here:
        IAdminOrden adminOrden = new FacadeAdminOrden();
        adminOrden.cancelarOrden(txtNumOrden.getText());
        cargarDatosTabla(jTPOrden, listaOrdenes);
    }//GEN-LAST:event_eliminarrBotonActionPerformed

    private void entregadaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregadaBotonActionPerformed
        IAdminOrden adminOrden = new FacadeAdminOrden();
        adminOrden.cancelarOrden(txtNumOrden.getText());
        cargarDatosTabla(jTPOrden, listaOrdenes);
    }//GEN-LAST:event_entregadaBotonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminarrBoton;
    private javax.swing.JButton entregadaBoton;
    private javax.swing.JTable jTPOrden;
    private javax.swing.JScrollPane tablaOrdenes;
    // End of variables declaration//GEN-END:variables

    private String obtenerNombreProductos(List<NuevoProductoDTO> productos) {
        return productos.stream()
                .map(p -> p.getNombre())
                .collect(Collectors.joining(", "));
    }

    public void mostrarTabla(List<Orden> listaOrdenes) {
//        cargarDatosTabla(jTPOrden, listaOrdenes);
    }
}
