/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.itson.bdavanzadas.presentacion;


import org.itson.bdavanzadas.adminTarjeta.VentanaPagarTarjeta3;
import org.itson.bdavanzadas.dtos.NuevaOrdenDTO;

/**
 *
 * @author Abe
 */
public class SeleccionarMetodo extends javax.swing.JDialog {

    private NuevaOrdenDTO ordenDTO;
    /**
     * Creates new form SeleccionarMetodo
     */
    public SeleccionarMetodo(java.awt.Frame parent, boolean modal, NuevaOrdenDTO ordenDTO) {
        super(parent, modal);
        this.ordenDTO = ordenDTO;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        btnTarjeta = new org.itson.bdavanzadas.componentes.BotonAzul();
        btnEfectivo = new org.itson.bdavanzadas.componentes.BotonAzul();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 265));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Selecciona el método de pago");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setPreferredSize(new java.awt.Dimension(397, 16));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 500, 44));

        btnTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        btnTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tarjeta.png"))); // NOI18N
        btnTarjeta.setText("Tarjeta");
        btnTarjeta.setToolTipText("");
        btnTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnTarjeta.setRadius(20);
        btnTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjetaActionPerformed(evt);
            }
        });
        getContentPane().add(btnTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 151, 52));

        btnEfectivo.setForeground(new java.awt.Color(255, 255, 255));
        btnEfectivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Efectivo.png"))); // NOI18N
        btnEfectivo.setText("Efectivo");
        btnEfectivo.setToolTipText("");
        btnEfectivo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnEfectivo.setRadius(20);
        btnEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfectivoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 151, 52));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfectivoActionPerformed
        this.dispose();
        VentanaPagarEfectivo VE = new VentanaPagarEfectivo(null, true, ordenDTO);
        VE.setVisible(true);
    }//GEN-LAST:event_btnEfectivoActionPerformed

    private void btnTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjetaActionPerformed
        this.dispose();
        VentanaPagarTarjeta3 VPT1 = new VentanaPagarTarjeta3(null, true,ordenDTO);
        VPT1.setVisible(true);
    }//GEN-LAST:event_btnTarjetaActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.itson.bdavanzadas.componentes.BotonAzul btnEfectivo;
    private org.itson.bdavanzadas.componentes.BotonAzul btnTarjeta;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
