/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.itson.bdavanzadas.presentacion;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import org.itson.bdavanzadas.adminOrden.FacadeAdminOrden;
import org.itson.bdavanzadas.adminOrden.IAdminOrden;
import org.itson.bdavanzadas.dtos.NuevaOrdenDTO;
/**
 *
 * @author Abe
 */
public class VentanaCancelar extends javax.swing.JDialog {

    private NuevaOrdenDTO ordenDTO;
    private IAdminOrden adminOrden;
    public static NuevaOrdenDTO ordenCancelada;
    public static boolean cancelado;

    /**
     * Creates new form VentanaCancelar
     */
    public VentanaCancelar(java.awt.Dialog parent, boolean modal, NuevaOrdenDTO ordenDTO) {
        super(parent, modal);
        initComponents();
        this.ordenDTO = ordenDTO;
        adminOrden = new FacadeAdminOrden();
        cancelado = false;
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (ordenCancelada != null) {
                    ordenCancelada.setNumeroOrden(-1);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        btnCancelarOrden = new org.itson.bdavanzadas.componentes.BotonPagar();
        btnRegresar = new org.itson.bdavanzadas.componentes.BotonCancelar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("¿Desea cancelar la orden?");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setPreferredSize(new java.awt.Dimension(397, 16));

        btnCancelarOrden.setText("Cancelar orden");
        btnCancelarOrden.setFocusTraversalPolicyProvider(true);
        btnCancelarOrden.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelarOrden.setRadius(15);
        btnCancelarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarOrdenActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegresar.setRadius(15);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnCancelarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        if (ordenCancelada != null) {
            ordenCancelada.setNumeroOrden(-1);
        }
        dispose();

    }//GEN-LAST:event_btnRegresarActionPerformed

    public static boolean seCancelo() {
        if (ordenCancelada != null) {
            if (ordenCancelada.getNumeroOrden() >= 0) {
                return true;
            } else {
                return false;
            }
        }
        else{
            return false;
        }

    }
    private void btnCancelarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarOrdenActionPerformed
        NuevaOrdenDTO ordenCancelad = adminOrden.cancelarOrden(ordenDTO);
        VentanaCancelar.ordenCancelada = ordenCancelad;
        dispose();
    }//GEN-LAST:event_btnCancelarOrdenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.itson.bdavanzadas.componentes.BotonPagar btnCancelarOrden;
    private org.itson.bdavanzadas.componentes.BotonCancelar btnRegresar;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
