/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.itson.bdavanzadas.presentacion;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.itson.bdavanzadas.dtos.NuevaOrdenDTO;
import org.itson.bdavanzadas.dtos.NuevoProductoDTO;
import static org.itson.bdavanzadas.presentacion.VentanaPagarEfectivo.ordenPagada;

/**
 *
 * @author Abe
 */
public class VentanaOrdenPagar extends javax.swing.JDialog {

    private NuevaOrdenDTO ordenDTO;
    DefaultTableModel modelo;

    /**
     * Creates new form JDialog
     */
    public VentanaOrdenPagar(java.awt.Frame parent, boolean modal, NuevaOrdenDTO ordenDTO) {
        super(parent, modal);
        this.ordenDTO = ordenDTO;
        initComponents();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");

        String fechaFormateada = formato.format(ordenDTO.getFecha());
        lblFecha.setText(fechaFormateada);
        lblNombre.setText(ordenDTO.getNombreCliente());
        lblNumOrden.setText(String.valueOf(ordenDTO.getNumeroOrden()));
        lblTotal.setText(String.valueOf(ordenDTO.getTotal()));

        consultarProductos();
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (VentanaPagarEfectivo.ordenPagada != null) {
                    VentanaPagarEfectivo.ordenPagada.setNumeroOrden(-1);
                }
            }
        });
    }

    private void consultarProductos() {
        List<NuevoProductoDTO> listaProductos;
        try {
            listaProductos = ordenDTO.getListaProductos();

            modelo = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return column == getColumnCount() - 1;
                }
            };

            modelo.addColumn("Producto");
            modelo.addColumn("Cantidad");
            modelo.addColumn("Precio");

            for (NuevoProductoDTO producto : listaProductos) {

                Object[] fila = {
                    producto.getNombre() + "(" + producto.getCategoria() + ")",
                    producto.getCantidad(),
                    producto.getPrecio()
                };
                modelo.addRow(fila);
            }

            tblProductos.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al consultar los productos de la ordenen " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new org.itson.bdavanzadas.componentes.Tabla();
        botonAzul2 = new org.itson.bdavanzadas.componentes.BotonAzul();
        botonAzul3 = new org.itson.bdavanzadas.componentes.BotonAzul();
        jLabel7 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblNumOrden = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(739, 598));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Lista de productos:");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(397, 16));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 230, 44));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Detalles de orden");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setPreferredSize(new java.awt.Dimension(397, 16));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, 44));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotal.setText("Nombre cliente: ");
        lblTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTotal.setPreferredSize(new java.awt.Dimension(397, 16));
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 198, 44));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Numero de orden:");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setPreferredSize(new java.awt.Dimension(397, 16));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 198, 44));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Fecha: ");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setPreferredSize(new java.awt.Dimension(397, 16));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 198, 44));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Total:");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setPreferredSize(new java.awt.Dimension(397, 16));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 198, 44));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 610, 160));

        botonAzul2.setForeground(new java.awt.Color(255, 255, 255));
        botonAzul2.setText("Continuar");
        botonAzul2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonAzul2.setRadius(25);
        botonAzul2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAzul2ActionPerformed(evt);
            }
        });
        getContentPane().add(botonAzul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 120, 40));

        botonAzul3.setForeground(new java.awt.Color(255, 255, 255));
        botonAzul3.setText("Cancelar");
        botonAzul3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonAzul3.setRadius(25);
        botonAzul3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAzul3ActionPerformed(evt);
            }
        });
        getContentPane().add(botonAzul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 120, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Nombre cliente: ");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setPreferredSize(new java.awt.Dimension(397, 16));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 198, 44));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombre.setText("Nombre cliente: ");
        lblNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblNombre.setPreferredSize(new java.awt.Dimension(397, 16));
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 198, 44));

        lblNumOrden.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNumOrden.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNumOrden.setText("Nombre cliente: ");
        lblNumOrden.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblNumOrden.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblNumOrden.setPreferredSize(new java.awt.Dimension(397, 16));
        getContentPane().add(lblNumOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 198, 44));

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFecha.setText("Nombre cliente: ");
        lblFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFecha.setPreferredSize(new java.awt.Dimension(397, 16));
        getContentPane().add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 198, 44));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAzul2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAzul2ActionPerformed
        SeleccionarMetodo SM = new SeleccionarMetodo(null, true, ordenDTO);
        this.dispose();
        SM.setVisible(true);
    }//GEN-LAST:event_botonAzul2ActionPerformed

    private void botonAzul3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAzul3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAzul3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.itson.bdavanzadas.componentes.BotonAzul botonAzul2;
    private org.itson.bdavanzadas.componentes.BotonAzul botonAzul3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumOrden;
    private javax.swing.JLabel lblTotal;
    private org.itson.bdavanzadas.componentes.Tabla tblProductos;
    // End of variables declaration//GEN-END:variables
}
