/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.itson.bdavanzadas.adminTarjeta;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.Timer;
import org.itson.bdavanzadas.AdminVentas.FacadeAdminVentas;
import org.itson.bdavanzadas.AdminVentas.IVentas;
import org.itson.bdavanzadas.dtos.MetodoPago;
import org.itson.bdavanzadas.dtos.NuevaOrdenDTO;
import org.itson.bdavanzadas.dtos.NuevaVentaDTO;

/**
 *
 * @author Abe
 */
public class VentanaPagarTarjeta3 extends javax.swing.JDialog {

    private static final int TIEMPO_MOSTRAR_DLG = 2000;
    private IVentas ventas;
    public static NuevaOrdenDTO ordenPagada;
    public NuevaOrdenDTO ordenDTO;
    public static boolean pagado;
    private int contadorCambios;
    private Timer timer;

    /**
     * Creates new form VentanaPagarTarjeta1
     */
    public VentanaPagarTarjeta3(java.awt.Frame parent, boolean modal, NuevaOrdenDTO ordenDTO) {
        super(parent, modal);
        initComponents();
        ventas = new FacadeAdminVentas();
        this.ordenDTO = ordenDTO;
        contadorCambios=0;
        
        timer = new Timer(2000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cambiarImagen();
                cambiarTexto();
                
                contadorCambios++;
                if (contadorCambios == 3) {
                    realizarVenta();
                }
            }
        });
        timer.start();
    }

    private void realizarVenta() {
        NuevaVentaDTO nuevaVenta = new NuevaVentaDTO();
        nuevaVenta.setFechaVenta(new Date());
        nuevaVenta.setMetodoPago(MetodoPago.TARJETA);
        nuevaVenta.setOrden(ordenDTO);
        nuevaVenta.setTotal((double) ordenDTO.getTotal());
        NuevaVentaDTO ventaPagada = ventas.registrarVenta(nuevaVenta);
        ;
        VentanaPagarTarjeta3.ordenPagada = ventaPagada.getOrden();

        System.out.println("ORDEEEEEEEEEEN");
        System.out.println(ordenPagada.getNumeroOrden());

    }

    private ImageIcon cargarImagen(String nombreImagen) {
        String rutaImagen = "src\\main\\resources\\imagenes\\" + nombreImagen;
        return new ImageIcon(getClass().getResource(rutaImagen));
    }

    private void cambiarImagen() {
        if (contadorCambios == 1) {
            ImageIcon imagenIcon = new ImageIcon("src\\main\\resources\\imagenes\\NIP.png");
            lblImagen.setIcon(imagenIcon);
        } else if (contadorCambios == 2) {
            ImageIcon imagenIcon = new ImageIcon("src\\main\\resources\\imagenes\\PagoAprobado.png");
            lblImagen.setIcon(imagenIcon);
        }
    }

    private void cambiarTexto() {
        if (contadorCambios == 1) {
            lblTexto.setText("Ingrese NIP");
        } else if (contadorCambios == 2) {
            lblTexto.setText("Pago aprobado");
        }
    }

    public static boolean sePago() {
        if (ordenPagada != null) {
            if (ordenPagada.getNumeroOrden() >= 0) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTexto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(739, 598));
        setResizable(false);

        lblImagen.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/InserteTarjeta.png"))); // NOI18N
        lblImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblImagen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblImagen.setMinimumSize(new java.awt.Dimension(260, 241));
        lblImagen.setPreferredSize(new java.awt.Dimension(397, 16));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pago con tarjeta");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setPreferredSize(new java.awt.Dimension(397, 16));

        lblTexto.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto.setText("Ingrese tarjeta");
        lblTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblTexto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTexto.setPreferredSize(new java.awt.Dimension(397, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
;
    }//GEN-LAST:event_btnContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblTexto;
    // End of variables declaration//GEN-END:variables
}
